[package]
name = "abe"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = "0.3.1"
env_logger = "0.11.8"
ipnet = "2.11.0"
log = "0.4.27"
nix = { version = "0.29.0", features = [ "default", "mount", "fs" ] }
uuid = { version = "1.16.0", features = [ "v4" ] }
